### PR TITLE
Swift 5 migration

### PR DESCRIPTION
**Pull request by LukasHromadnik**
Please test it if it is alright for you.

### CODE REVIEW

**Comment by thii** [comment]
Looks like Xcode 10.2 is not available on Travis CI yet.

**Comment by LukasHromadnik** [comment]
Updated travis.yml to use the newest Xcode

**Comment by nysander** [comment]
@thii when do you plan new release with this PR included?

**Comment by thii** [comment]
@nysander Sorry for the delay. I'm going to put a release later today.

**Comment by onurgenes** [comment]
I am also waiting for new release. Thanks in advance.

**Comment by nysander** [comment]
And question why issues are disabled? There is no way to report not working Pod

**Comment by thii** [comment]
This has now been released as 1.7.0.

**Comment by nysander** [comment]
Thx

**Comment by thii** [comment]
> And question why issues are disabled? There is no way to report not working Pod

Because I don't have time to handle issues, and I expect people to submit pull requests instead 🙃

**Comment by x1911** [comment]
1.7.0 runs error with same setting
1.5.1 works perfect, any change not show in index?
thank you for your time

**Comment by thii** [comment]
> 1.7.0 runs error with same setting
> 1.5.1 works perfect, any change not show in index?
> thank you for your time
> 
Could you let us know what error it was?

**Comment by x1911** [comment]
i use same code
```
extension UILabel{
    
     func StyleCellIcon(_ number:Int){
     let icon : [FontAwesome] = [.listUl, .newspaper, .wineBottle, .questionCircle, .venus, .smileBeam, .bomb, .personBooth, .star]
     
        let num = number >= icon.count ? (icon.count - 1) : number

     self.font = UIFont.fontAwesome(ofSize: 20, style: .solid)
        self.text = String.fontAwesomeIcon(name:icon[num])
     self.textAlignment = .center
     self.clipsToBounds = true
     }
}
```

it works with 1.5.1
image


but in 1.7.0 totally diffent
image

**Comment by thii** [comment]
There is a font update in 1.7.0. Could you try replacing it with the old
font used in 1.5.1 to see if it works?

**Comment by x1911** [comment]
i use it with pod update direct,
1.5.1 works
in 1.7.0 where should i replace?

**Comment by thii** [comment]
Please try replacing the font files manually after doing a pod install.

**Pull request merged**
