### PR TITLE
Patch @King-Wizard

### PR DESCRIPTION
**Pull request by King-Wizard**
Updated the project and the code to Swift 2.0, iOS 9 and Xcode 7 + added NSLayoutConstraints to the unique UIViewController via storyboard + Fixed Travis bug + modified README.md file + bumped to 0.6.0 and updated FontAwesome.swift.podspec + created a tag named 0.6.0

### CODE REVIEW

**Comment by RaviDesai** [comment]
Thank you King-Wizard.  I'm in need of this patch also.  Hopefully it can get merged to master quickly.

**Comment by thii** [comment]
@King-Wizard Your commit is a mess.

**Comment by King-Wizard** [comment]
Why is it the mess? 

It is stupid to say that it is the mess without giving us your arguments on why.

Actually me and @RaviDesai use my repository and branch because it works, while your did not work when I sent this pull request.

I did not put any mess in the project, I just migrated the code plus the project to iOS 9 and Swift 2 + I added auto-layout constraints in the storyboard, that's all.

On top of that, I fixed your Travis configuration file and everything was fine on Travis.

I do not really understand your reaction.

Anyway @RaviDesai, feel free to use my branch entitled 'patch-1' on my repository.

Note: by the way there is a difference between a big commit and a messy commit. Next time just say that you do not want to take the time to merge it because the commit has modified too many files and I will understand.

**Comment by King-Wizard** [comment]
Ok sorry, I see the problem, I am going to merge my 'patch-1' branch with your 'master' branch on my side and re-send you a pull request, as soon as it will be done.

**Pull request closed without merging**
