### PR TITLE
4.5 font awesome update

### PR DESCRIPTION
**Pull request by shams-ahmed**

### CODE REVIEW

**Comment by nanoxd** [comment]
Looks good! :+1:, I would suggest making this a minor bump to `0.7.0` due to the addition of new icons though

**Comment by shams-ahmed** [comment]
@nanoxd done!

**Comment by nanoxd** [comment]
Thanks! I'll merge this in. @thii Can you push out the podspec file?

**Comment by thii** [comment]
@shams-ahmed @nanoxd Thanks a lot! I've just push v0.7.0 to CocoaPods.

**Comment by shams-ahmed** [comment]
@thii thanks!

**Pull request merged**
