### PR TITLE
Xcode7b6 - advance() to .advanceBy(n)

### PR DESCRIPTION
**Pull request by mpclarkson**

### CODE REVIEW

**Comment by dcunited001** [comment]
I was about to submit a pull for this same issue, but looks like @mpclarkson beat me to the punch. 

is this not compatible with swift 1.x? is it possible to add a protocol like [Strideable](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_Strideable_Protocol/index.html)?

**Comment by mpclarkson** [comment]
Check out a commit from a month or so ago - it should be swift 1 compatible.

**Comment by thii** [comment]
Merged to `swift-2.0` branch. You shouldn't make a pull request from your master though.

**Comment by mpclarkson** [comment]
Oops, sorry.

**Pull request closed without merging**
